### ISSUE TITLE
Pull latest Slate

### ISSUE THREAD

**Issue by bep** [bep/docuapi#10]
Tried to do it, but seems they have done some CSS changes that also needs some adjustments on this sidse.

**Comment by humumbus** [comment]
👍

**Comment by Octopixell** [comment]
Hi @bep great work on this so far! Any ideas when we can expect this update? I'm very very new to Hugo so I'm not sure if there's a way I can help speed this up? Let me know if there's something I can look at to maybe help with a fix.

**Comment by bep** [comment]
>Any ideas when we can expect this update? 

No. See my comment above. I'm very busy in other areas, so if someone "other than me" want to hace a look at it, go ahead.

**Comment by Octopixell** [comment]
@bep ok no problem ;) Could you be a little more specific on what you didn't manage to fix or what still needs to be done? A checklist maybe, then I could have a go at it. Would love to try.

**Comment by bep** [comment]
If you start a hugo server with the branch I started above, it should be obvious. The checklist is: Get it working.

**Comment by bep** [comment]
Note: I have finished porting this to the new Slate today, but as this was mostly an exercise/testing the upcoming (and really cool) Hugo version -- I need to wait for that release before I can merge. Hopefully some time late next week.

See https://github.com/bep/docuapi/tree/hugo-modules for my work.

**Comment by bep** [comment]
done
