### ISSUE TITLE
Demo site isn't working

### ISSUE THREAD

**Issue by coliff** [bep/docuapi#18]
http://docuapi.com/

**Comment by bep** [comment]
I just let the domain expire ...

**Comment by coliff** [comment]
Ah, i see the demo is at: https://docuapi.netlify.com/ now. can you change the URL in the repo?

**Comment by bep** [comment]
I thought I did? Is it mention other than in the README?

**Comment by coliff** [comment]
Yep, next to the project description at the top at: https://github.com/bep/docuapi
