### ISSUE TITLE
Provide javascript source code

### ISSUE THREAD

**Issue by eric-taix-teads** [bep/docuapi#22]
First thanks for your work: It's really amazing

Except if I missed something but I can't find your javascript source code...
So it's impossible to change / fix anything. I think that providing minify version of javascript is fine, but can you also push on Github all source file ?

It will able anyone to fix javascript issue if any.

**Comment by bep** [comment]
I only have some small set of JS "overrides" in https://github.com/bep/docuapi/blob/master/assets/javascripts/app/_lang.js

The rest are pulled in from https://github.com/lord/slate via bundler.go. Note that this theme was made before Hugo got SCSS and bundler support, but I have not have had any time to get this theme up to date ...
