### ISSUE TITLE
The update of theme produce some unexpected things

### ISSUE THREAD

**Issue by ldez** [bep/docuapi#28]
- the theme colors are not the same
- the menu are always expended and cannot be collapsed
- some icons are missing (ex: search, note)

Is it expected?

Before:
![before](https://user-images.githubusercontent.com/5674651/63115478-90187680-bf97-11e9-9ae4-56a5e5f74576.png)

After:
![after](https://user-images.githubusercontent.com/5674651/63115480-90187680-bf97-11e9-8d4e-777847c4064e.png)

**Comment by bep** [comment]
It looks fine here:

https://docuapi.netlify.com/

I assume you are still in a sub path in the baseURL?  I quickly fixed the build error, but there may be some other hard coded paths in there.

**Comment by ldez** [comment]
I have the same issue with icons and menu on https://docuapi.netlify.com/

**Comment by ldez** [comment]
If I take the image in the readme, there is also some color changes in the demo.

Before:
![](https://raw.githubusercontent.com/bep/docuapi/master/images/screenshot.png)

After:
![Screenshot_2019-08-15 Introduction – DocuAPI Example Site](https://user-images.githubusercontent.com/5674651/63116410-da025c00-bf99-11e9-8bab-ef2d1ca84674.png)

**Comment by bep** [comment]
The README image is old and outdated.

I see the search icon issue, but only in Safari. I will look into that, but not tonight.

**Comment by ldez** [comment]
ok, for the icons I think it's just a font issue.

But the menu issue is related to more structural changes.

**Comment by bep** [comment]
So, the menu changes from 1.1 to 1.2 was due to an update of Slate. I should probably have upped major versions to v2, but that would probably have made some troubles with Hugo Modules. You can probably still use v1.1 if you really want.

**Comment by ldez** [comment]
FYI I take https://lord.github.io/slate/ as reference for menu and colors, maybe I miss something.

**Comment by ldez** [comment]
The menu issue is related to:
https://github.com/bep/docuapi/blob/e36e058d215588567972325a82cc348f3fffbcb0/layouts/_default/list.html#L7-L14

I'm still trying to find the root cause of color and icons.

**Comment by ldez** [comment]
The issue with colors come from a difference between some SCSS variables:

https://github.com/bep/docuapi/blob/e36e058d215588567972325a82cc348f3fffbcb0/assets/scss/slate/_variables.scss#L10-L27

https://github.com/lord/slate/blob/de496848c1e7b7116371ae25944aced1c22c47a9/source/stylesheets/_variables.scss#L24-L41

**Comment by ldez** [comment]
I fixed the menu and the colors in #29 but for the icons I don't know enough the Hugo theme processing to fix the problem (I think it's related to the path of font, inside the CSS, before the processing.
