### ISSUE TITLE
Not working properly when rendering TOC in langauges other than English

### ISSUE THREAD

**Issue by katopway** [bep/docuapi#34]
When language of the doc is switched to other languages like Chinese, or Norwegian like in the example site, the ```h2``` items in TOC can not be  expanded or collapsed automatically while scrolling the doc page, or being displayed when clicking on any ```h1``` items with children.

Is there any way to make it work in other languages?

**Comment by bep** [comment]
I'll have a look.

**Comment by rrbarrero** [comment]
Same here: Error: Syntax error, unrecognized expression: #1-introducci%c3%b3n all.js:1750:8

**Comment by bep** [comment]
Yes, I debugged it down to some JS line, but my 10 minutes spent on this didn't find a fix ...

**Comment by rrbarrero** [comment]
If it can helps, in commit f2cb5423932c3542077daa77e24b4aa4effd6ff8 works for me.

**Comment by bep** [comment]
I have added a fix for this. Note that for this fix to work you need Hugo >= 0.61 and the Goldmark markdown renderer (default).
