### ISSUE TITLE
Support for deeper submenu items level in ToC

### ISSUE THREAD

**Issue by khos2ow** [bep/docuapi#37]
Currently the maximum supported depth for rendering ToC is 2 (basically h1 and h2). I was about to enhance this and send a PR but decided to start the discussion first.

- was this intentional? or hasn't been done simply because of lack of interest or request of the feature?
- I was going to enable up to 3 levels depth (h1, h2 and h3). If we're going to consider this enhancement, what the maximum depth should be? In my use case 3 is enough (and I can argue in general it would be).

Any thoughts, comments or suggestions on the matter?

**Comment by bep** [comment]
>was this intentional? 

2 seemed like a fine number, but it could certainly be made configurable...

**Comment by khos2ow** [comment]
So would you like this to be configurable or just increased (to for example 3 or 4 or ..)?

**Comment by bep** [comment]
>So would you like this to be configurable or just increased (to for example 3 or 4 or ..)?

It needs to be configurable and default 2. I picked 2 because I like ... 2, and I want to keep it.

**Comment by bep** [comment]
I take that back. I guess we could increase it to 3 or 4 by default without it starting to look odd.

**Comment by khos2ow** [comment]
I did a very ugly quick hack and 3 seems to be doable, fast. I'll try to come up with a PR to potentially support up to 4 and may be even configurable.
But to me 4 levels deep in the menu looks like a little bit too deep and may be rearranging from the API owner would be more logical than the theme supporting it.

**Comment by zyxep** [comment]
What is the status on this one?

I know Slate has this, https://github.com/slatedocs/slate/wiki/Deeper-Nesting which should make it possible.
My end goal is to have this structure:
- APIS
- - api1
- - - docs for api1
- - - docs for api1
- - - docs for api1
- - api2
- - - docs for api2
- - - docs for api2
- - - docs for api2
- - api3
- - - docs for api3
- - - docs for api3
- - - docs for api3

**Comment by khos2ow** [comment]
We actually ended up settling on two level deep menu and restructured our content instead, but I should be able to revive the work I had started for this if there's an interest for it.

**Comment by zyxep** [comment]
It would be nice :)

I think my Product Designer would love to keep the old menu structure we currently have.

**Comment by khos2ow** [comment]
I submitted a PR which should be a good starting point IMO. As it stands it cannot be merged yet (I've described it in #63), but essentially one particular css rule is missing.
