### ISSUE TITLE
hard-code hash in header 

### ISSUE THREAD

**Issue by AyKarsi** [bep/docuapi#52]
I would like to control the generated hash, so that I can link between pages and safely update page titles. 

e.g. main.md
```
----
weight: 17
title: hello world
hash: "hello"
---

# hello world
```
expected resullt `http://localhost:1313/#hello`
current result: `http://localhost:1313/#hello-world`

I'm a Hugo noob, so please execuse if I'm missing something obvious.

**Comment by bep** [comment]
Try:

```md
----
weight: 17
title: hello world
hash: "hello"
---

# hello world {#hello}
```
