### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by long-tran** [bep/docuapi#53]
Hei guys, can you please have a very short installation guide to get this up?
Thanks.

**Comment by maelle** [comment]
I've just got it working locally, I had to read https://discourse.gohugo.io/t/hugo-modules-for-dummies/20758 and https://gohugo.io/hugo-modules/

I installed Go cf https://github.com/bep/docuapi/issues/51#issuecomment-587407833

**Comment by metachris** [comment]
git clone git@github.com:bep/docuapi.git
    cd docuapi/exampleSite
    hugo serve

**Comment by long-tran** [comment]
Why would you run `hugo server` in the /exampleSite folder?
Shouldn't we run it in the root folder?

**Comment by bep** [comment]
>Shouldn't we run it in the root folder?

No. The root folder represents a theme and not a standalone site.
