### ISSUE TITLE
Slate notes and warnings not working

### ISSUE THREAD

**Issue by katopway** [bep/docuapi#57]
Seems notes and warnings from slate syntax is not working, also as in the example site.

![image](https://user-images.githubusercontent.com/56426196/87122103-c8fbc100-c2b6-11ea-852a-7abfdf71be6e.png)

Can you help to have a look.

Not sure whether related to specific version, currenly with go1.13.6, hugo version 0.73.0 and the latest of docuapi.

**Comment by metachris** [comment]
It's because hugo doesn't allow html by default. You need to add

    [markup.goldmark.renderer]
        unsafe = true
