### ISSUE TITLE
HUGO won't start server with LoveIt theme

### ISSUE THREAD

**Issue by antedoro** [bep/docuapi#60]
Hi guys,
may be this is a stupid question but I can't start using this theme because when I start server from command line the answer is:

"_Module "LoveIt" not found; either add it as a Hugo Module or store it in "/Users/antedoro".: module does not exist_".

Hugo version: v0.74.3/extended

Thi is steps I made:

1. hugo new site myLoveItSite
2. cd myLoveItSite
3. git clone https://github.com/dillonzq/LoveIt.git themes/LoveIt
4. hugo server -D

It's the same answer when I copy exampleSite folder contents in root folder.

Can you take me some advice?

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
