### ISSUE TITLE
Paths are not relative for stylesheets, so github pages hosting doesn't work

### ISSUE THREAD

**Issue by thrivingresearch** [bep/docuapi#7]
if using github pages in a repo, the non-relative paths "<link href='/slate/stylesheets/screen.css' rel="stylesheet" media="screen" />" are broken - because they are really located at /reponame/slate/etc

**Comment by bep** [comment]
I'm not sure I follow you.

I load every stylesheet using `relURL` (a function I have written myself, which I'm pretty confident is doing the right thing). So, assuming you have set the `baseURL` correctly, it should just work. 

https://github.com/bep/docuapi/blob/master/layouts/partials/styles.html#L1

**Comment by thrivingresearch** [comment]
You're 100% correct. I was wrong, my mistake :)

(to anyone else reading... don't forget to update baseURL when you push 😅)
