### ISSUE TITLE
All language codes are displayed on first load or refresh

### ISSUE THREAD

**Issue by techmagus** [bep/docuapi#74]
Issue: When visiting (or refreshing) a DocuAPI website, all lang codes are displayed. A user have to click any language at the top bar to filter it out.

Tested on:
* Demo site: https://docuapi.netlify.app/
* SemWeb docs: https://semweb.youronly.one

DocuAPI version:
* Demo site: not sure but I'm assuming it's v2.0.1
* SemWeb docs: v2.0.1 as per `go.mod` file and `module.toml`
> `go.mod`
```go
github.com/bep/docuapi v1.5.2
github.com/bep/docuapi/v2 v2.0.1
```
> `module.toml`
```toml
[[imports]]
  path = "github.com/bep/docuapi/v2"
```

Platform: Ubuntu 20.04 LTS

Browsers:
* Firefox 95.0b7 (dev channel)
* Edge 97.0.1069.0 (dev channel)

Hugo version: v0.89.3

Shalom!

**Comment by bep** [comment]
Thanks, yes this seem to have slipped through when I upgraded to AlpineJS. I will fix.

**Comment by techmagus** [comment]
> Thanks, yes this seem to have slipped through when I upgraded to AlpineJS. I will fix.

Hi, just tested but it seems not to be working. I followed what was in the commit 7fd543c  and changed it a little bit on my local and seemed to work.

From:
```js
initLangs: function(tabs) {
	debug('initLangs', tabs);
	this.changeLanguage(0);
	tabs[0].active = true;
	this.tabs = tabs;
```

To:
```js
initLangs: function(tabs) {
	debug('initLangs', tabs);
	tabs[0].active = true;
	this.tabs = tabs;
	this.changeLanguage(0);
```

Not sure if it affected something else.

Shalom.

**Comment by bep** [comment]
OK, sorry, that's probably a timing issue --- the correct way is, I think, to do it in the `nextTick` callback, I will take another shot at it.
