### ISSUE TITLE
How does this project incorporate slate?

### ISSUE THREAD

**Issue by poseisharp** [bep/docuapi#83]
I'm sorry this is not an actual issue and just a question but I couldn't find another way to ask.

I'm trying to understand how does this project incorporate slate, but all I found was slate's styling.
My current understanding is that this theme only uses slate's styling and the rest is from this project, even if that's correct I still would like to know how does this theme obtain the styling, is it copied, is it generated in some way?

**Comment by bep** [comment]
In it's latest version it's less Slate than it used to be, but the gist of it lives in

https://github.com/bep/docuapi/blob/5bfdc7d366ef2de58dc4e52106ad474d06410907/config.toml#L14

This uses Hugo Modules (backed by Go Modules) to mount remote folders into the project (stylesheets etc.).
