### ISSUE TITLE
Custom Header anchor link

### ISSUE THREAD

**Issue by Sheikh-Aman** [bep/docuapi#88]
Currently if I write a heading such as:

> ### Step 1 - Setup

Then it generates an anchor URL for this header like the following:
`example.com/api/#step-1---setup`

That `step-1---setup` just looks horrible in the URL.  
Is there a way to customize it right in the markdown where we specify the heading?
Something like:
> ### Step 1 - Setup <a=setup>

Gracias!

**Comment by bep** [comment]
You can use markdown attributes, e.g.:

```
## Step 1 - Setup {#my-pretty-id}
```

**Comment by Sheikh-Aman** [comment]
Lovely.
I had tried multiple combinations except this one.
Thanks so much!
