### ISSUE TITLE
How to change favicon?

### ISSUE THREAD

**Issue by kostya-konev** [bep/docuapi#92]
I just copied repository and deploy it to netlify. So deployment goes from exampleSite folder. How do I change favicon? I tried many ways, such as:
1. Adding favicon.ico in "static" folder that is located in the root directory.

2. Adding favicon.ico in "static/images" folder that is located in the root directory and creating head.html file in "layouts/partials" folder that is located in the root directory and put there <link rel="icon" href="{{ "images/favicon.ico" | relURL }}">

3. Adding favicon.ico in "static/images" folder that is located in the exampleSite directory and creating head.html file in "layouts/partials" folder that is located in the exampleSite directory and put there <link rel="icon" href="{{ "images/favicon.ico" | relURL }}">

Also I tried different href values, like href="images/favicon.ico", href="{{ relURL "images/favicon.ico" }}"

Nothing works.

**Comment by bep** [comment]
There's no favicon in the default templates, but you can add the markup yourself. Simplest if probably to just add a hook template, see `partials/hook_head_end.html`:

https://github.com/bep/docuapi#hooks
