### ISSUE TITLE
Bug - Same row.ids allocated to two different elements with same text

### ISSUE THREAD

**Issue by roshanjonah** [bep/docuapi#94]
Thanks for this great theme @bep 

Two different .md files with different weights and content but the same heading are randomly allocated with the same row.id causing both of them to open their sub-menus simultaneously while scrolling. Please take a look at the photo below.

![CleanShot 2023-04-14 at 16 20 47@2x](https://user-images.githubusercontent.com/20136098/231941814-b29fa5e4-4cdb-49da-86b5-248caee5b9b4.png)

They both have the address - http://localhost:1313/#query-parameters-10

I've cleared the cache. I tried publishing to the online site - the issue remains.

**Comment by bep** [comment]
OK, then I don't understand, because theres duplicate headings in the example site here:

https://docuapi.netlify.app/

There's code to detect this and increment a counter.

**Comment by bep** [comment]
As a workaround you can assign the IDs manually in markdown, e.g.

````
## Query Parameters {#some-unique-id}
```
